name: Deploy to AWS S3

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AKIASC5F3RADCM47MX6C }}
          aws-secret-access-key: ${{ secrets.qYvOrZb4ySx1CjX/4/cR29aJ3Y4Qiwo4HTJPni38 }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: |
          aws s3 sync ./ s3://bojjanaresh-portfolio \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --delete
